services:
  - type: web
    name: tidgo-pwa
    runtime: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /sw.js
        name: Cache-Control
        value: no-cache
      - path: /manifest.json
        name: Content-Type
        value: application/manifest+json
